apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "banklo-cards-issuer.fullname" . }}
spec:
  selector:
    matchLabels:
      app: coinsure-cards
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]