{{- if .Values.kong.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: banklo-cards-issuer-do-not-preserve-host
route:
  preserve_host: false
upstream:
  host_header: {{ include "banklo-cards-issuer.fullname" . }}.cards.svc
{{end}}