apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "banklo-cards-issuer.fullname" . }}
spec:
  hosts:
    - {{ include "banklo-cards-issuer.fullname" . }}
  http:
    - fault:
        abort:
          httpStatus: 500
          percentage:
            value: 20
      route:
        - destination:
            host: {{ include "banklo-cards-issuer.fullname" . }}
            subset: v1
